### ISSUE TITLE
inconsistent version

### ISSUE THREAD

**Issue by Kochise** [eerimoq/argparse_addons#3]
When I use cantools :

`ImportError: cannot import name 'Integer' from 'argparse_addons' (C:\Program Files\Spyder\Python\lib\site-packages\argparse_addons.py)
`

What is installed :

`argparse_addons-0.1.0.dist-info
`

What I try to do :

`python -m pip install --upgrade argparse_addons>=0.7.0
`

What I get :

```
WARNING: Discarding https://files.pythonhosted.org/packages/82/3c/893305cd6bef596cb4059f794ba3b69d59edcb96794bec683fff5a437d0a/argparse_addons-0.7.0.tar.gz#sha256=f5da0fe676953e39bee7a6d0a9b2f5ccdcbf9d6a6b9929997caf8f6c6b23a5fb (from https://pypi.org/simple/argparse-addons/) (requires-python:>=3.6). Requested argparse_addons from https://files.pythonhosted.org/packages/82/3c/893305cd6bef596cb4059f794ba3b69d59edcb96794bec683fff5a437d0a/argparse_addons-0.7.0.tar.gz#sha256=f5da0fe676953e39bee7a6d0a9b2f5ccdcbf9d6a6b9929997caf8f6c6b23a5fb has inconsistent version: filename has '0.7.0', but metadata has '0.1.0'
WARNING: Discarding https://files.pythonhosted.org/packages/76/6d/a4342d968eeff3a5f35556a52a1310717558612fedbaa1c7e80626163ce4/argparse_addons-0.6.0.tar.gz#sha256=3823071e9d66bc7b521ade37d22faf03ad08c91adf210cb21cd523a9074a6b63 (from https://pypi.org/simple/argparse-addons/). Requested argparse_addons from https://files.pythonhosted.org/packages/76/6d/a4342d968eeff3a5f35556a52a1310717558612fedbaa1c7e80626163ce4/argparse_addons-0.6.0.tar.gz#sha256=3823071e9d66bc7b521ade37d22faf03ad08c91adf210cb21cd523a9074a6b63 has inconsistent version: filename has '0.6.0', but metadata has '0.1.0'
WARNING: Discarding https://files.pythonhosted.org/packages/3e/ab/46d987156fa0be5c324454612d7ffbacd97ed44115abe8e9813dd2cc4c33/argparse_addons-0.5.0.tar.gz#sha256=30f51d2b9556e10873751d79f3a58dc23ac3af3426d0b84bbd464581a7e6f335 (from https://pypi.org/simple/argparse-addons/). Requested argparse_addons from https://files.pythonhosted.org/packages/3e/ab/46d987156fa0be5c324454612d7ffbacd97ed44115abe8e9813dd2cc4c33/argparse_addons-0.5.0.tar.gz#sha256=30f51d2b9556e10873751d79f3a58dc23ac3af3426d0b84bbd464581a7e6f335 has inconsistent version: filename has '0.5.0', but metadata has '0.1.0'
WARNING: Discarding https://files.pythonhosted.org/packages/48/09/c2e0699c900e03273584c467b907d9e20264a2ab6ac9bd3f3caa9e3e5d81/argparse_addons-0.4.0.tar.gz#sha256=54d8bfc76cdd8076e3dcdd29433a6e49ace10da447c8c8f8ddd82dc8764d1fa0 (from https://pypi.org/simple/argparse-addons/). Requested argparse_addons from https://files.pythonhosted.org/packages/48/09/c2e0699c900e03273584c467b907d9e20264a2ab6ac9bd3f3caa9e3e5d81/argparse_addons-0.4.0.tar.gz#sha256=54d8bfc76cdd8076e3dcdd29433a6e49ace10da447c8c8f8ddd82dc8764d1fa0 has inconsistent version: filename has '0.4.0', but metadata has '0.1.0'
WARNING: Discarding https://files.pythonhosted.org/packages/66/fb/c86f135078f80ffedc25dfca6100e7f9664b5f55a04466f6cbe5b95bbfa0/argparse_addons-0.3.0.tar.gz#sha256=f6f46231d889a79f5cc82f9ba09c38d32db3b604b1fc6747d37c14f6678b5d40 (from https://pypi.org/simple/argparse-addons/). Requested argparse_addons from https://files.pythonhosted.org/packages/66/fb/c86f135078f80ffedc25dfca6100e7f9664b5f55a04466f6cbe5b95bbfa0/argparse_addons-0.3.0.tar.gz#sha256=f6f46231d889a79f5cc82f9ba09c38d32db3b604b1fc6747d37c14f6678b5d40 has inconsistent version: filename has '0.3.0', but metadata has '0.1.0'
WARNING: Discarding https://files.pythonhosted.org/packages/2c/c4/8220182fc4c9b45282ffb6c3cf9504120d0f5d43e2900efd04bdf1880372/argparse_addons-0.2.0.tar.gz#sha256=412c6960bf88671fc669e6acdf0f470b422e125eb6a5a357acd4e7679678a94c (from https://pypi.org/simple/argparse-addons/). Requested argparse_addons from https://files.pythonhosted.org/packages/2c/c4/8220182fc4c9b45282ffb6c3cf9504120d0f5d43e2900efd04bdf1880372/argparse_addons-0.2.0.tar.gz#sha256=412c6960bf88671fc669e6acdf0f470b422e125eb6a5a357acd4e7679678a94c has inconsistent version: filename has '0.2.0', but metadata has '0.1.0'
```

And of course the requested version 0.7.0 doesn't install...

When I try to install the package by hand :

`python Lib\site-packages\argparse_addons\setup.py
`

I get :

```
Traceback (most recent call last):
  File "Lib\site-packages\argparse_addons\setup.py", line 7, in <module>
    version=argparse_addons.__version__,
AttributeError: module 'argparse_addons' has no attribute '__version__'
```

Any help ?

Regards.

**Comment by eerimoq** [comment]
I've never seen anything like it. What is your python version?

**Comment by Kochise** [comment]
Python in Spyder 4.2.5 :

```
C:\Program Files\Spyder\Python>python -m pip --version
pip 21.0.1 from C:\Program Files\Spyder\Python\lib\site-packages\pip (python 3.7)

c:\Program Files\Spyder\Python>python.exe
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by Kochise** [comment]
In a fresh installation of Spyder 5.0.0 :

```
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.22.0 -- An enhanced Interactive Python.

In [1]: !pip install --upgrade argparse_addons
Collecting argparse_addons
  Downloading argparse_addons-0.7.0.tar.gz (3.8 kB)
  Downloading argparse_addons-0.6.0.tar.gz (3.5 kB)
  Downloading argparse_addons-0.5.0.tar.gz (3.5 kB)
  Downloading argparse_addons-0.4.0.tar.gz (3.5 kB)
  Downloading argparse_addons-0.3.0.tar.gz (3.6 kB)
  Downloading argparse_addons-0.2.0.tar.gz (3.0 kB)
  Downloading argparse_addons-0.1.0-py2.py3-none-any.whl (2.8 kB)
Installing collected packages: argparse-addons
Successfully installed argparse-addons-0.1.0
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\spyder\python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-ddveuhc9\\argparse-addons_7595d41e40124774b69a2871d0b51ef2\\setup.py'"'"'; __file__='"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-ddveuhc9\\argparse-addons_7595d41e40124774b69a2871d0b51ef2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\dkoch\AppData\Local\Temp\pip-pip-egg-info-h0yuunr0'
         cwd: C:\Users\dkoch\AppData\Local\Temp\pip-install-ddveuhc9\argparse-addons_7595d41e40124774b69a2871d0b51ef2\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dkoch\AppData\Local\Temp\pip-install-ddveuhc9\argparse-addons_7595d41e40124774b69a2871d0b51ef2\setup.py", line 4, in <module>
        import argparse_addons
    ModuleNotFoundError: No module named 'argparse_addons'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/82/3c/893305cd6bef596cb4059f794ba3b69d59edcb96794bec683fff5a437d0a/argparse_addons-0.7.0.tar.gz#sha256=f5da0fe676953e39bee7a6d0a9b2f5ccdcbf9d6a6b9929997caf8f6c6b23a5fb (from https://pypi.org/simple/argparse-addons/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\spyder\python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-ddveuhc9\\argparse-addons_dba3373daf0f42418b2bfd20f0549ab2\\setup.py'"'"'; __file__='"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-ddveuhc9\\argparse-addons_dba3373daf0f42418b2bfd20f0549ab2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\dkoch\AppData\Local\Temp\pip-pip-egg-info-21czut82'
         cwd: C:\Users\dkoch\AppData\Local\Temp\pip-install-ddveuhc9\argparse-addons_dba3373daf0f42418b2bfd20f0549ab2\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dkoch\AppData\Local\Temp\pip-install-ddveuhc9\argparse-addons_dba3373daf0f42418b2bfd20f0549ab2\setup.py", line 4, in <module>
        import argparse_addons
    ModuleNotFoundError: No module named 'argparse_addons'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/76/6d/a4342d968eeff3a5f35556a52a1310717558612fedbaa1c7e80626163ce4/argparse_addons-0.6.0.tar.gz#sha256=3823071e9d66bc7b521ade37d22faf03ad08c91adf210cb21cd523a9074a6b63 (from https://pypi.org/simple/argparse-addons/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\spyder\python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-ddveuhc9\\argparse-addons_421d7b0403d544ca834602500a688426\\setup.py'"'"'; __file__='"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-ddveuhc9\\argparse-addons_421d7b0403d544ca834602500a688426\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\dkoch\AppData\Local\Temp\pip-pip-egg-info-bx983sup'
         cwd: C:\Users\dkoch\AppData\Local\Temp\pip-install-ddveuhc9\argparse-addons_421d7b0403d544ca834602500a688426\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dkoch\AppData\Local\Temp\pip-install-ddveuhc9\argparse-addons_421d7b0403d544ca834602500a688426\setup.py", line 4, in <module>
        import argparse_addons
    ModuleNotFoundError: No module named 'argparse_addons'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/3e/ab/46d987156fa0be5c324454612d7ffbacd97ed44115abe8e9813dd2cc4c33/argparse_addons-0.5.0.tar.gz#sha256=30f51d2b9556e10873751d79f3a58dc23ac3af3426d0b84bbd464581a7e6f335 (from https://pypi.org/simple/argparse-addons/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\spyder\python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-ddveuhc9\\argparse-addons_225b62022ae94aa0a603c619c0cd9290\\setup.py'"'"'; __file__='"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-ddveuhc9\\argparse-addons_225b62022ae94aa0a603c619c0cd9290\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\dkoch\AppData\Local\Temp\pip-pip-egg-info-5vfdcxzc'
         cwd: C:\Users\dkoch\AppData\Local\Temp\pip-install-ddveuhc9\argparse-addons_225b62022ae94aa0a603c619c0cd9290\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dkoch\AppData\Local\Temp\pip-install-ddveuhc9\argparse-addons_225b62022ae94aa0a603c619c0cd9290\setup.py", line 4, in <module>
        import argparse_addons
    ModuleNotFoundError: No module named 'argparse_addons'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/48/09/c2e0699c900e03273584c467b907d9e20264a2ab6ac9bd3f3caa9e3e5d81/argparse_addons-0.4.0.tar.gz#sha256=54d8bfc76cdd8076e3dcdd29433a6e49ace10da447c8c8f8ddd82dc8764d1fa0 (from https://pypi.org/simple/argparse-addons/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\spyder\python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-ddveuhc9\\argparse-addons_2c5e3224419f432eb65eea112e7006c7\\setup.py'"'"'; __file__='"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-ddveuhc9\\argparse-addons_2c5e3224419f432eb65eea112e7006c7\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\dkoch\AppData\Local\Temp\pip-pip-egg-info-e_m_14pc'
         cwd: C:\Users\dkoch\AppData\Local\Temp\pip-install-ddveuhc9\argparse-addons_2c5e3224419f432eb65eea112e7006c7\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dkoch\AppData\Local\Temp\pip-install-ddveuhc9\argparse-addons_2c5e3224419f432eb65eea112e7006c7\setup.py", line 4, in <module>
        import argparse_addons
    ModuleNotFoundError: No module named 'argparse_addons'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/66/fb/c86f135078f80ffedc25dfca6100e7f9664b5f55a04466f6cbe5b95bbfa0/argparse_addons-0.3.0.tar.gz#sha256=f6f46231d889a79f5cc82f9ba09c38d32db3b604b1fc6747d37c14f6678b5d40 (from https://pypi.org/simple/argparse-addons/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\spyder\python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-ddveuhc9\\argparse-addons_96f7e52767354072a4b5539c695abb46\\setup.py'"'"'; __file__='"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-ddveuhc9\\argparse-addons_96f7e52767354072a4b5539c695abb46\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\dkoch\AppData\Local\Temp\pip-pip-egg-info-0aunak8z'
         cwd: C:\Users\dkoch\AppData\Local\Temp\pip-install-ddveuhc9\argparse-addons_96f7e52767354072a4b5539c695abb46\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dkoch\AppData\Local\Temp\pip-install-ddveuhc9\argparse-addons_96f7e52767354072a4b5539c695abb46\setup.py", line 4, in <module>
        import argparse_addons
    ModuleNotFoundError: No module named 'argparse_addons'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2c/c4/8220182fc4c9b45282ffb6c3cf9504120d0f5d43e2900efd04bdf1880372/argparse_addons-0.2.0.tar.gz#sha256=412c6960bf88671fc669e6acdf0f470b422e125eb6a5a357acd4e7679678a94c (from https://pypi.org/simple/argparse-addons/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

In [2]: !pip cache purge
Files removed: 89

In [3]: !pip install --upgrade argparse_addons
Requirement already satisfied: argparse_addons in c:\program files\spyder\python\lib\site-packages (0.1.0)
Collecting argparse_addons
  Downloading argparse_addons-0.7.0.tar.gz (3.8 kB)
  Downloading argparse_addons-0.6.0.tar.gz (3.5 kB)
  Downloading argparse_addons-0.5.0.tar.gz (3.5 kB)
  Downloading argparse_addons-0.4.0.tar.gz (3.5 kB)
  Downloading argparse_addons-0.3.0.tar.gz (3.6 kB)
  Downloading argparse_addons-0.2.0.tar.gz (3.0 kB)
WARNING: Discarding https://files.pythonhosted.org/packages/82/3c/893305cd6bef596cb4059f794ba3b69d59edcb96794bec683fff5a437d0a/argparse_addons-0.7.0.tar.gz#sha256=f5da0fe676953e39bee7a6d0a9b2f5ccdcbf9d6a6b9929997caf8f6c6b23a5fb (from https://pypi.org/simple/argparse-addons/) (requires-python:>=3.6). Requested argparse_addons from https://files.pythonhosted.org/packages/82/3c/893305cd6bef596cb4059f794ba3b69d59edcb96794bec683fff5a437d0a/argparse_addons-0.7.0.tar.gz#sha256=f5da0fe676953e39bee7a6d0a9b2f5ccdcbf9d6a6b9929997caf8f6c6b23a5fb has inconsistent version: filename has '0.7.0', but metadata has '0.1.0'
WARNING: Discarding https://files.pythonhosted.org/packages/76/6d/a4342d968eeff3a5f35556a52a1310717558612fedbaa1c7e80626163ce4/argparse_addons-0.6.0.tar.gz#sha256=3823071e9d66bc7b521ade37d22faf03ad08c91adf210cb21cd523a9074a6b63 (from https://pypi.org/simple/argparse-addons/). Requested argparse_addons from https://files.pythonhosted.org/packages/76/6d/a4342d968eeff3a5f35556a52a1310717558612fedbaa1c7e80626163ce4/argparse_addons-0.6.0.tar.gz#sha256=3823071e9d66bc7b521ade37d22faf03ad08c91adf210cb21cd523a9074a6b63 has inconsistent version: filename has '0.6.0', but metadata has '0.1.0'
WARNING: Discarding https://files.pythonhosted.org/packages/3e/ab/46d987156fa0be5c324454612d7ffbacd97ed44115abe8e9813dd2cc4c33/argparse_addons-0.5.0.tar.gz#sha256=30f51d2b9556e10873751d79f3a58dc23ac3af3426d0b84bbd464581a7e6f335 (from https://pypi.org/simple/argparse-addons/). Requested argparse_addons from https://files.pythonhosted.org/packages/3e/ab/46d987156fa0be5c324454612d7ffbacd97ed44115abe8e9813dd2cc4c33/argparse_addons-0.5.0.tar.gz#sha256=30f51d2b9556e10873751d79f3a58dc23ac3af3426d0b84bbd464581a7e6f335 has inconsistent version: filename has '0.5.0', but metadata has '0.1.0'
WARNING: Discarding https://files.pythonhosted.org/packages/48/09/c2e0699c900e03273584c467b907d9e20264a2ab6ac9bd3f3caa9e3e5d81/argparse_addons-0.4.0.tar.gz#sha256=54d8bfc76cdd8076e3dcdd29433a6e49ace10da447c8c8f8ddd82dc8764d1fa0 (from https://pypi.org/simple/argparse-addons/). Requested argparse_addons from https://files.pythonhosted.org/packages/48/09/c2e0699c900e03273584c467b907d9e20264a2ab6ac9bd3f3caa9e3e5d81/argparse_addons-0.4.0.tar.gz#sha256=54d8bfc76cdd8076e3dcdd29433a6e49ace10da447c8c8f8ddd82dc8764d1fa0 has inconsistent version: filename has '0.4.0', but metadata has '0.1.0'
WARNING: Discarding https://files.pythonhosted.org/packages/66/fb/c86f135078f80ffedc25dfca6100e7f9664b5f55a04466f6cbe5b95bbfa0/argparse_addons-0.3.0.tar.gz#sha256=f6f46231d889a79f5cc82f9ba09c38d32db3b604b1fc6747d37c14f6678b5d40 (from https://pypi.org/simple/argparse-addons/). Requested argparse_addons from https://files.pythonhosted.org/packages/66/fb/c86f135078f80ffedc25dfca6100e7f9664b5f55a04466f6cbe5b95bbfa0/argparse_addons-0.3.0.tar.gz#sha256=f6f46231d889a79f5cc82f9ba09c38d32db3b604b1fc6747d37c14f6678b5d40 has inconsistent version: filename has '0.3.0', but metadata has '0.1.0'
WARNING: Discarding https://files.pythonhosted.org/packages/2c/c4/8220182fc4c9b45282ffb6c3cf9504120d0f5d43e2900efd04bdf1880372/argparse_addons-0.2.0.tar.gz#sha256=412c6960bf88671fc669e6acdf0f470b422e125eb6a5a357acd4e7679678a94c (from https://pypi.org/simple/argparse-addons/). Requested argparse_addons from https://files.pythonhosted.org/packages/2c/c4/8220182fc4c9b45282ffb6c3cf9504120d0f5d43e2900efd04bdf1880372/argparse_addons-0.2.0.tar.gz#sha256=412c6960bf88671fc669e6acdf0f470b422e125eb6a5a357acd4e7679678a94c has inconsistent version: filename has '0.2.0', but metadata has '0.1.0'
 ```
