### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by jkljkjkjk** [eerimoq/argparse_addons#5]
HI there

can you help to check why the syntax error appears when I pip install cantools? 

pip and python version is 2.7

error is :
bb@bb:/usr/bin$ pip install argparse-addons
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Collecting argparse-addons
  Using cached argparse_addons-0.6.0.tar.gz (3.5 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jJ1TbU/argparse-addons/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jJ1TbU/argparse-addons/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-zTOf33
         cwd: /tmp/pip-install-jJ1TbU/argparse-addons/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jJ1TbU/argparse-addons/setup.py", line 4, in <module>
        import argparse_addons
      File "argparse_addons.py", line 19
        f'{string} is not in the range {self.minimum}..{self.maximum}')
                                                                     ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

thanks a  lot

**Comment by eerimoq** [comment]
Python 2 is not supported.
